### ISSUE TITLE
Write/edit Contribution Guides on how to contribute to documentation

### ISSUE THREAD

**Issue by silverhook** [Pelican-Elegant/elegant#411] opened 2019-07-01 08:28 UTC
Now that our documentation resides in https://github.com/Pelican-Elegant/elegant/tree/master/documentation/content we need to fix the contribution guides to direct people to it.

Instances where it needs to be fixed:

- https://github.com/Pelican-Elegant/elegant/blob/master/CONTRIBUTING.md
- https://elegant.oncrashreboot.com/contribute i.e. https://github.com/Pelican-Elegant/elegant/blob/master/documentation/content/pages/contribute.md

**Comment by talha131** [comment] 2019-07-01 09:06
Duplicate of https://github.com/Pelican-Elegant/elegant/issues/343 It's a WIP.

**Closed by talha131** 2019-07-01 09:06 UTC
Labels: project documentation
