### ISSUE TITLE
"Contents"  appears in article even with no TOC

### ISSUE THREAD

**Issue by codecachet** [Pelican-Elegant/elegant#278] opened 2019-02-18 20:31 UTC
Template checks `{% if article.toc %}`. However, `article.toc` appears to be full of html.  In my case: `<div class="toc"> <ul></ul>  </div>`.

**Comment by talha131** [comment] 2019-02-21 13:30
@codecachet Do you have extract_toc plugin?

Kindly share the source code of your blog so that we can reproduce it?

**Comment by codecachet** [comment] 2019-02-22 21:26
I'll try to figure out what is wrong, and let you know. Thanks!

**Comment by talha131** [comment] 2019-02-22 21:34
@codecachet yes please do report back so that we can fix the issue or update our documentation.

**Comment by iranzo** [comment] 2019-04-04 08:39
@codecachet were you able to dig further? is this still relevant?

**Comment by codecachet** [comment] 2019-04-06 20:27
I think the issue is the Table of Contents Markdown extension itself - as long as you have [TOC] in your Markdown, it will always return the `<ul>...</ul>`, even if there is nothing in the table of contents list, and the `<ul>` contains no `<li>`s.

**Comment by iranzo** [comment] 2019-04-08 19:17
I was checking the extract_toc and it uses beautiful soup to extract it from the generated document, so the theme shows it if the article contains the [TOC]

**Comment by iranzo** [comment] 2019-06-09 09:40
As a way forward, user should not add [TOC] or either we can hack the post generated code (dirty) to remove it if no TOC has been created (empty one)

I vote for 1 which is simpler and then add only '[TOC]' where intended

**Comment by talha131** [comment] 2019-06-09 16:55
A better solution is to modify the `extract_toc` plugin to

1. Extract toc whether it is empty or not
1. Do not populate the `article.toc` field if the list is empty

**Comment by iranzo** [comment] 2019-06-09 17:35
extract_toc should then get an issue to have it fixed there?

**Comment by talha131** [comment] 2019-06-09 17:39
Yeah, an issue the pelican-plugins repository linking to this issue should
be enough to close this issue.

**Comment by talha131** [comment] 2019-07-05 04:05
This issue should be fixed in extract_toc plugin.

**Closed by talha131** 2019-07-05 04:05 UTC
Labels: need information

**Comment by talha131** [comment] 2019-07-05 04:19
@codecachet see https://github.com/getpelican/pelican-plugins/pull/1156
