### ISSUE TITLE
Fix HTML 5 validation issues

### ISSUE THREAD

**Issue by talha131** [Pelican-Elegant/elegant#132] opened 2014-09-06 14:35 UTC
1. https://twitter.com/svenkreiss/status/508087712390598656
2. https://github.com/svenkreiss/pelican-theme-validator#elegant
3. http://www.svenkreiss.com/pelican-theme-validator/elegant/html5validator.txt

**Comment by silverhook** [comment] 2016-01-06 16:50
That doesn’t seem that bad, actually. Should be easily fixed.

The `pubdate` errors can probably be fixed by replacing that attribute with `itemprop="published"` [as W3C seems to suggest] (http://www.w3.org/TR/microdata/#names:-the-itemprop-attribute)

As for the other bugs, [W3C’s own unicorn validator doesn’t seem to replicate them, even when using the same URL as Sven did](https://validator.w3.org/unicorn/check?ucn_uri=www.svenkreiss.com%2Fpelican-theme-validator%2Felegant%2Foutput%2F&doctype=Inline&charset=%28detect%20automatically%29&ucn_task=conformance#).

The bigger issue is passing the CSS3 test, where Elegant has over 600 issues, but getting at least HTML5 compliant would be great for now! :smile_cat:

**Comment by silverhook** [comment] 2016-01-06 17:05
As for `<meta name="copyright">` issue, Unicorn doesn’t flag it, but Sven is right that it’s not in [W3C’s specifications for the `meta` tag](http://www.w3.org/TR/html5/document-metadata.html#the-meta-element).

I think we can simply drop that tag, since it’s effectively a duplicate of the `<meta name="author">` tag.

This is a really low hanging fruit. I’m happy to make a pull request, if there is interest.

**Comment by talha131** [comment] 2018-12-18 16:30
@silverhook What's the status of this issue?

**Comment by silverhook** [comment] 2018-12-18 16:35
#151 should have fixed all except for the `<meta name="copyright">` issue, which IMHO should be removed as well as it’s (still) not part of the W3C specs, even though it doesn’t cause an error in the validator.

As I said in https://github.com/Pelican-Elegant/elegant/pull/151#issuecomment-447075312

> As for the copyright meta tag – at least when I wrote the PR – the `<meta name="copyright">` was not a valid HTML5 tag, which is why I removed it. I can try it again without it and see if it still breaks.
> 
> Also we cannot be 100% sure that the `AUTHOR` is also the copyright holder in the article/page. It is very likely though, especially for personal blogs.

If anyone sees use in having the tag remain, let’s keep it. Otherwise, I suggest to purge it in favour of keeping the `<meta name="author">` tag, which _is_ a W3C-valid meta tag.

**Comment by talha131** [comment] 2018-12-18 16:38
> Otherwise, I suggest to purge it in favour of keeping the <meta name="author"> tag, which is a W3C-valid meta tag.

Lets do it. Can you handle this? If so please assign the issue to yourself.

**Comment by silverhook** [comment] 2018-12-18 20:47
> > Otherwise, I suggest to purge it in favour of keeping the  tag, which is a W3C-valid meta tag.
> 
> Lets do it. Can you handle this? If so please assign the issue to yourself.

Can do.

**Closed as completed** 2018-12-19 09:23 UTC
