### ISSUE TITLE
When user lands on 404 page, autofill search box with url slug, if available

### ISSUE THREAD

**Issue by iranzo** [Pelican-Elegant/elegant#476] opened 2019-08-01 06:27 UTC
## Mandatory Step

- [x] I am using latest production release of Elegant

## Recommended Step

- [ ] I have attached link to my blog source code repository, so that developers can try to reproduce the issue at the end
- [ ] I can't my source code but I have linked my pelican configuration files to help developers reproduce the issue

## Description

**Describe the bug**
Currently, Pelican generates a page for tags/categories which lists all of them. This is ok, but it would be great to also have pointer to 'tags' as in url, for example:

- https://next.elegant.oncrashreboot.com/tags/admonitions

vs what we actually have at:

- https://next.elegant.oncrashreboot.com/tags#admonitions-ref

Would it be possible to enable 'both' ?

**To Reproduce**

Generate any website with elegant

**Expected behavior**

Additional url for just the tags, this will help people coming from other themes to Pelican not to get 'broken urls'

**Comment by talha131** [comment] 2019-08-01 06:33
This is a not a bug. It's an intentional feature. Elegant is a zen inspired minimal theme.

Let me know why a separate tag page is better than what we currently have? Any specific feature that we can't add to current design?

**Comment by iranzo** [comment] 2019-08-01 06:38
Hi Talha , no, it's not better, but if we can generate 'both' 'or' make the 404 page to 'redirect' to the tags#reftag it would be good.

Just happened because my previous theme was using it and got email from 'search console' complaining that url was no longer available

**Comment by talha131** [comment] 2019-08-01 06:43
To solve this problem, you need to setup redirects from your `example.com/tags/eg` to `example.com/tags#eg`.

How to accomplish this? It depends on your choice of hosting provider.

We use Netlify, which lets us define redirect rules in a text file. Here is our rules

https://github.com/Pelican-Elegant/elegant/blob/master/documentation/content/extra/_redirects

You would need to do something similar with your site.

If your host does not provide this option, then you can use Elegant redirection feature

https://elegant.oncrashreboot.com/article-redirect

but I don't think this a better solution. For your use case, a 301 redirect is a better solution.

**Comment by iranzo** [comment] 2019-08-01 06:46
Yes, I know, or use `.htaccess.. as with regular website but wanted to see if there's something we could do from Elegant side to have it covered (if we were willing to pursue that goal)

**Comment by iranzo** [comment] 2019-08-01 06:54
Alternatively, what I did at my website before using pelican, was to use a custom 404 that redirected to 'search', like the 404, to pass the url field except site to the:

https://next.elegant.oncrashreboot.com/search.html?q=admonition


If we convert '/' in the url to 'spaces' and redirect or provide link to user to 'perform search' on website will make it easier

**Comment by talha131** [comment] 2019-08-01 06:55
Sorry. I don't think we should add a feature that changes a core feature of Elegant that was added explicitly, when 301 redirection is a much more suitable solution.

**Comment by talha131** [comment] 2019-08-01 06:57
> If we convert '/' in the url to 'spaces' and redirect or provide link to user to 'perform search' on website will make it easier

Let me know if I understand you correctly, when user gets to a 404, you want to autofill the search field with the url.

**Comment by iranzo** [comment] 2019-08-01 07:11
Yes, or even 'autosubmit' it and show it with a custom header saying 'the page you were looking for wasn't found, here are some alternates that might be helpful'

**Comment by talha131** [comment] 2019-08-01 07:12
Agree. That would be nice to have. 

Can you take up this issue?

**Comment by iranzo** [comment] 2019-08-01 07:40
I can try to!

**Comment by talha131** [comment] 2019-08-01 11:12
I have added this task to roadmap, assigned to you and updated labels.

There is no rush. Take your time to implement. But if you lose interest then please update this issue tracker.

**Comment by iranzo** [comment] 2019-08-01 12:32
I think we might need to do it with javascript, as the site gets rendered before uploading, hence the 404.html template should contain the code to convert the current location into filling the form default value

are we ok with that approach? other ideas?

**Comment by talha131** [comment] 2019-08-01 13:02
> the 404.html template should contain the code to convert the current location into filling the form default value

That's the only way to do it.

1. A JS script that works only inside 404 page
1. If URL is present (after removing the domain part) then place it inside search box
1. else do nothing

**Comment by iranzo** [comment] 2019-08-05 12:22
can you check https://github.com/Pelican-Elegant/elegant/pull/478 ?

Contains a link to an example on the netlify site. If behaviour is ok, I can proceed to documenting

**Comment by iranzo** [comment] 2019-08-05 12:24
We might also consider to remove some 'other words' like 'tags' etc to make it easier to find results and maybe tuning the text above the search box to 'remind' user to press 'search' (or directly perform it)

**Closed** 2019-08-14 17:39 UTC
Labels: enhancement
