### ISSUE TITLE
[BUG] W3C-Validator complains about section tags

### ISSUE THREAD

**Issue by jackdewinter** [Pelican-Elegant/elegant#473] opened 2019-07-31 04:23 UTC
## Description

**Describe the bug**
Similar to https://github.com/Pelican-Elegant/elegant/issues/103, there is some cleanup that can be done in this area.

The big one is the use of section tags... these are flooding the output of the validator so it is difficult to see any other issues.

**To Reproduce**
1. Go to the [Elegant home page](https://github.com/Pelican-Elegant/elegant)
2. Click on the "Build Passing" or "Build Failing" button.
3. Scroll down until you hit the w3c_validator section.

Issues I can see:
- Section lacks heading. Consider using “h2”-“h6” elements to add identifying headings to all sections.
    - in [this article](https://stackoverflow.com/questions/24155024/w3c-html-validation-error-section-lacks-heading-consider-using-h2-h6-elements) it suggests that sections SHOULD have a header to identify the section to screen readers.
   - is there any reason we are using section tags instead of div tags?
- "The “type” attribute is unnecessary for JavaScript resources." and
- "The “language” attribute on the “script” element is obsolete. You can safely omit it."
   - is there any backwards compatibility reason why we are keeping these?

**Expected behavior**
W3c validator should be clean and stay clean.

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- Version: 75.0.3770.142 (Official Build) (64-bit)

**Comment by talha131** [comment] 2019-07-31 21:51
Duplicate of of #251

**Closed by talha131** 2019-07-31 21:51 UTC
Labels: bug

**Comment by talha131** [comment] 2019-07-31 21:56
@all-contributors please add @jackdewinter for bug, doc, content
