### ISSUE TITLE
Accordion is not working in production

### ISSUE THREAD

**Issue by cmcai0104** [Pelican-Elegant/elegant#189] opened 2018-12-05 02:56 UTC
When I deploy my blog on GitHub, the  Collapsible Comments cannot uncollapse which is available in localhost.

Here is my blog address: https://cmcai0104.github.io

And deploy code:
```
pelican content -s publishconf.py
ghp-import output -b master
git push origin master
```

And this is my pelicanconf.py document:
```
#!/usr/bin/env python
# -*- coding: utf-8 -*- #
from __future__ import unicode_literals

AUTHOR = u'CaiChunming'
SITENAME = u"CMCai's Blog"
SITEURL = 'https://cmcai0104.github.io'

#PATH = 'content'
DATE_FORMATS = {'zh':'%b %d, %Y'}
TIMEZONE = 'Asia/Shanghai'
DEFAULT_LANG = u'zh'

# Feed generation is usually not desired when developing
FEED_ALL_ATOM = None
CATEGORY_FEED_ATOM = None
TRANSLATION_FEED_ATOM = None
#AUTHOR_FEED_ATOM = None
#AUTHOR_FEED_RSS = None

# Social widget
SOCIAL = (('Twitter','https://twitter.com/CaiChunming0104'),
('Github','https://github.com/cmcai0104'),('Email','mailto:hzxsccm678335@163.com'),)

DEFAULT_PAGINATION = 10

# Uncomment following line if you want document-relative URLs when developing
#RELATIVE_URLS = True

#MD_EXTENSIONS = ['codehilite(css_class=highlight)','extra','toc(permalnk=true)']
MARKDOWN = {
    'extension_configs': {
        'markdown.extensions.codehilite': {'css_class': 'highlight'},
        'markdown.extensions.extra': {},
        'markdown.extensions.meta': {},
        'markdown.extensions.toc': {'permalink':'true'},
    },
    'output_format': 'html5',
    'extensions' : ['extra']
}
MARKUP = ('md', 'ipynb')
PLUGIN_PATHS = [ './pelican-plugins/' ]
PLUGINS = ['ipynb.markup', 'extract_toc', 'tipue_search','sitemap','liquid_tags.img','neighbors','latex','related_posts','assets','series','share_post'
#,'multi_part'
]
SITEMAP = {
    'format': 'xml',
    'priorities': {
        'articles': 0.5,
        'indexes': 0.5,
        'pages': 0.5
    },
    'changefreqs': {
        'articles': 'monthly',
        'indexes': 'daily',
        'pages': 'monthly'
    }
}

TYPOGRIFY = True
THEME = './pelican-themes/pelican-elegant'
DEFAULT_PAGINATION = False

DIRECT_TEMPLATES = (('index', 'tags', 'categories','archives', 'search', '404'))
STATIC_PATHS = ['theme/images', 'images'] #图片放在content/theme/images
TAG_SAVE_AS = ''
CATEGORY_SAVE_AS = ''
AUTHOR_SAVE_AS = ''
USE_SHORTCUT_ICONS = True

# Defaults
DEFAULT_CATEGORY = 'Miscellaneous'
USE_FOLDER_AS_CATEGORY = False
ARTICLE_URL = u'{slug}'
PAGE_URL = u'{slug}'
PAGE_SAVE_AS = u'{slug}.html'

# Elegant Labels
SOCIAL_PROFILE_LABEL = u'Stay in Touch'
RELATED_POSTS_LABEL = 'Keep Reading'
SHARE_POST_INTRO = 'Like this post? Share on:'
COMMENTS_INTRO = u'So what do you think? Did I miss something? Is any part unclear? Leave your comments below.'

DISQUS_SITENAME = u'cmcai0104'
TWITTER_USERNAME = u'CaiChunming'
FEATURED_IMAGE = './content/theme/images/apple-touch-icon-152x152.png'

# Landing Page
LANDING_PAGE_ABOUT = ({'title':'Welcome to my field', 'details':"""本人主要关注>概率统计及随机分析相关内容。对于量化金融、数据科学等方面有过相关的科研经历，也参
与过图像处理等科研项目。目前主要从事数据科学领域相关工作。\n 写此博客仅仅是对自>己学习的一个记录。若有任何问题欢迎联系我: hzxsccm678335@163.com 。\n 希望通过此>博客对学过的知识进行总结梳理。望多多给予宝贵意见，谢谢🙏！！"""})
PROJECTS = [
#{    'name': 'Logpad + Duration',
#    'url': 'https://github.com/talha131/logpad-plus-duration#logpad--duration',
#    'description': 'Vim plugin to emulate Windows Notepad logging feature,'
#    ' and log duration of each entry'},
    {'name': 'Elegant Theme for Pelican',
    'url': 'http://oncrashreboot.com/pelican-elegant',
    'description': 'A clean and distraction free theme, with search and a'
    ' lot more unique features, using Jinja2 and Bootstrap'}
]
```

**Comment by silverhook** [comment] 2018-12-05 10:21
Hi @cmcai0104, thanks for the bug report. Unfortunately, I don’t have comments on my blog, so I can’t help you there myself, but I’m sure others can.

e.g. @calfzhou, @talha131, @debiatan and many others use Disqus as well – can anyone help debug this issue?

**Comment by talha131** [comment] 2018-12-06 03:39
@cmcai0104 I had a look on your blog. The problem is not limited to Disqus comments. Accordion is not working even on Categories page.

https://cmcai0104.github.io/categories.html

At the moment, I don't understand the reason. I confirmed that bootstrap CSS file is present in your blog.
 Could it be that bootstrap JS file is missing? Can you please confirm it?

BTW, you may want to change the fav icon of your site.

**Comment by cmcai0104** [comment] 2018-12-06 04:30
@talha131  
Maybe the problem is about jquery whose address is http, so it will not load at https.

And the fav icon I will change latter.

**Comment by AWegnerGitHub** [comment] 2018-12-06 04:35
That is correct @cmcai0104 . The mixed content HTTP/HTTPS on the jQuery include is a problem. This is here: https://github.com/Pelican-Elegant/elegant/blob/d01538eb61cffb4e356d40888391620423585aad/templates/base.html#L95 

This is fixed in PR #131

**Comment by talha131** [comment] 2018-12-06 05:12
Thank you @AWegnerGitHub 

@cmcai0104 can you please confirm that @AWegnerGitHub solution works for you.

**Comment by talha131** [comment] 2018-12-06 05:33
Remove `https` from the URL. So the final URL is `//code.jquery.com/jquery.min.js`

**Comment by silverhook** [comment] 2018-12-06 07:49
@cmcai0104, also, we should have #131 merged soon and aim at a 2.0 release in the foreseeable future. So if you don’t want to get your hands dirty, you can also wait for the new release :)

**Comment by cmcai0104** [comment] 2018-12-06 07:54
@talha131  I have try it, but it does't work.

**Comment by cmcai0104** [comment] 2018-12-06 07:55
@silverhook 👌，thank you.

**Comment by talha131** [comment] 2018-12-06 07:59
Just saw the source code of your categories page. The URL is not updated

![](https://i.imgur.com/Tev9vpI.png)

**Comment by cmcai0104** [comment] 2018-12-06 08:08
But I have already remove 'http' of the jquery url in elegant/templates/base.html, search.html

**Comment by talha131** [comment] 2018-12-06 09:32
@cmcai0104 the issue is definitely caused due to SSL. Few parts of the page are not using SSL, which causes browser to block them.

You need to make sure https version of jqeury gets added to the final output.

Here is a gif the shows disabling SSL on your site fixes the issue.

![](https://i.imgur.com/pA8d1zm.gifv)

I don't understand why `//code.jquery....` didn't work. Can you try

1. `https://jquery....` full URL with `https`.
1. Lastly, you can, for the time being, host jquery on your own site. Just to confirm. To do that, dowload jquery.min.js and place it inside the static folder and point the theme to it. (This suggestion may be difficult to follow if you are unfamiliar with the theme code).

**Comment by iranzo** [comment] 2018-12-09 23:01
I can confirm that #200 solves the issue and accordion opens

**Comment by talha131** [comment] 2018-12-10 03:21
@cmcai0104 can you please merge changes from the master, and confirm that this issue is fixed?

**Comment by cmcai0104** [comment] 2018-12-11 03:15
@talha131  @iranzo 

Thank you! It is available! 

I forget to change the themes location in pelicanconf.py

**Comment by talha131** [comment] 2018-12-11 04:02
@cmcai0104 Thank you for responding back. As for categories, tags and archives, please see this issue #203. Basically you have to set variables `TAGS_URL` and so on. Please report any update regarding links in #203.

**Closed by talha131** 2018-12-11 04:02 UTC
